import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:habit_tracker/features/habit/domain/entities/habit_entity.dart';
import 'package:habit_tracker/features/habit/presentation/bloc/habit_bloc.dart';
import 'package:habit_tracker/features/categories/presentation/bloc/category_bloc.dart';
import 'package:habit_tracker/features/categories/domain/entities/category_entity.dart';
import 'package:habit_tracker/features/habit/presentation/widgets/reminder_settings_widget.dart';
import 'package:habit_tracker/core/services/notification_service.dart';
import 'package:habit_tracker/injection_container.dart' as di;

class AddHabitPage extends StatefulWidget {
  const AddHabitPage({super.key});

  @override
  State<AddHabitPage> createState() => _AddHabitPageState();
}

class _AddHabitPageState extends State<AddHabitPage> {
  final _nameController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _formKey = GlobalKey<FormState>();

  String _selectedIcon = '🦁'; // Default icon
  Color _selectedColor = Colors.blue;
  HabitFrequency _frequency = HabitFrequency.daily;
  String? _selectedCategoryId;

  // Reminder settings
  bool _reminderEnabled = false;
  TimeOfDay? _reminderTime;
  List<int>? _reminderDays;

  final List<String> _animalIcons = [
    '🦁',
    '🐯',
    '🐘',
    '🦒',
    '🦓',
    '🦍',
    '🦏',
    '豹', // Leopard as emoji is 🐆
    '🐊',
    '🐫',
  ];

  // Replacing characters with emojis if needed, but the original list had 🦁, 🐯, etc.
  // I will use the finalized list from our previous standardization.
  final List<String> _finalAnimalIcons = [
    '🦁',
    '🐯',
    '🐘',
    '🦒',
    '🦓',
    '🦍',
    '🦏',
    '🐆',
    '🐊',
    '🐫',
  ];

  final List<Color> _colors = [
    Colors.blue,
    Colors.red,
    Colors.green,
    Colors.orange,
    Colors.purple,
    Colors.teal,
    Colors.pink,
    Colors.indigo,
  ];

  @override
  void initState() {
    super.initState();
    context.read<CategoryBloc>().add(LoadCategories());
  }

  @override
  void dispose() {
    _nameController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _onSavePressed() async {
    if (_formKey.currentState!.validate()) {
      // Validate reminder settings if enabled
      if (_reminderEnabled) {
        if (_reminderTime == null) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Please select a reminder time'),
              backgroundColor: Colors.orange,
            ),
          );
          return;
        }
        if (_reminderDays == null || _reminderDays!.isEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Please select at least one day for reminders'),
              backgroundColor: Colors.orange,
            ),
          );
          return;
        }
      }

      // Convert TimeOfDay to DateTime for storage
      DateTime? reminderDateTime;
      if (_reminderTime != null) {
        reminderDateTime = DateTime(
          2000,
          1,
          1,
          _reminderTime!.hour,
          _reminderTime!.minute,
        );
      }

      final newHabit = HabitEntity(
        id: '', // Will be generated by Supabase
        userId: '', // Will be set in Repository
        name: _nameController.text.trim(),
        description: _descriptionController.text.trim(),
        iconAsset: _selectedIcon,
        colorHex: _selectedColor.value.toRadixString(16),
        frequency: _frequency,
        categoryId: _selectedCategoryId,
        reminderEnabled: _reminderEnabled,
        reminderTime: reminderDateTime,
        reminderDays: _reminderDays,
        createdAt: DateTime.now(),
        archived: false,
      );

      context.read<HabitBloc>().add(AddHabitEvent(newHabit));
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<HabitBloc, HabitState>(
      listener: (context, state) {
        if (state is HabitLoaded) {
          if (!mounted) return;
          context.pop();
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Habit added successfully! 🎊')),
          );
        } else if (state is HabitError) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: Colors.redAccent,
            ),
          );
        }
      },
      builder: (context, state) {
        final isLoading = state is HabitLoading;

        return Scaffold(
          appBar: AppBar(title: const Text('New Habit')),
          body: GestureDetector(
            onTap: () => FocusScope.of(context).unfocus(),
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Icon Selector
                    const Text(
                      'Icon',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    SizedBox(
                      height: 90,
                      child: ListView.builder(
                        scrollDirection: Axis.horizontal,
                        itemCount: _finalAnimalIcons.length,
                        padding: const EdgeInsets.symmetric(vertical: 8),
                        itemBuilder: (context, index) {
                          final icon = _finalAnimalIcons[index];
                          final isSelected = _selectedIcon == icon;
                          return GestureDetector(
                            onTap: () {
                              setState(() => _selectedIcon = icon);
                            },
                            child: AnimatedContainer(
                              duration: const Duration(milliseconds: 300),
                              width: 60,
                              height: 60,
                              margin: const EdgeInsets.only(right: 12),
                              decoration: BoxDecoration(
                                color: isSelected
                                    ? _selectedColor.withAlpha(40)
                                    : Theme.of(context)
                                          .colorScheme
                                          .surfaceVariant
                                          .withAlpha(50),
                                shape: BoxShape.circle,
                                border: Border.all(
                                  color: isSelected
                                      ? _selectedColor
                                      : Colors.transparent,
                                  width: 2,
                                ),
                              ),
                              alignment: Alignment.center,
                              child: Text(
                                icon,
                                style: TextStyle(
                                  fontSize: 28,
                                  decoration: isSelected ? null : null,
                                ),
                              ),
                            ),
                          );
                        },
                      ),
                    ),
                    const SizedBox(height: 16),

                    // Color Selector
                    const Text(
                      'Color',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    SizedBox(
                      height: 50,
                      child: ListView.builder(
                        scrollDirection: Axis.horizontal,
                        itemCount: _colors.length,
                        itemBuilder: (context, index) {
                          final color = _colors[index];
                          final isSelected = _selectedColor == color;
                          return GestureDetector(
                            onTap: () => setState(() => _selectedColor = color),
                            child: Container(
                              width: 40,
                              height: 40,
                              margin: const EdgeInsets.only(right: 12),
                              decoration: BoxDecoration(
                                color: color,
                                shape: BoxShape.circle,
                                border: Border.all(
                                  color: isSelected
                                      ? Colors.white
                                      : Colors.transparent,
                                  width: 2,
                                ),
                                boxShadow: isSelected
                                    ? [
                                        BoxShadow(
                                          color: color.withAlpha(100),
                                          blurRadius: 4,
                                        ),
                                      ]
                                    : null,
                              ),
                              child: isSelected
                                  ? const Icon(
                                      Icons.check,
                                      color: Colors.white,
                                      size: 20,
                                    )
                                  : null,
                            ),
                          );
                        },
                      ),
                    ),
                    const SizedBox(height: 24),

                    TextFormField(
                      controller: _nameController,
                      textInputAction: TextInputAction.next,
                      decoration: const InputDecoration(
                        labelText: 'Habit Name',
                        hintText: 'e.g. Read 10 pages',
                        prefixIcon: Icon(Icons.edit_outlined),
                      ),
                      validator: (value) => (value == null || value.isEmpty)
                          ? 'Please enter a name'
                          : null,
                    ),
                    const SizedBox(height: 16),

                    TextFormField(
                      controller: _descriptionController,
                      textInputAction: TextInputAction.done,
                      maxLines: 3,
                      decoration: const InputDecoration(
                        labelText: 'Description (Optional)',
                        hintText: 'Why do you want to do this?',
                        prefixIcon: Icon(Icons.description_outlined),
                      ),
                    ),
                    const SizedBox(height: 24),

                    const Text(
                      'Category',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    BlocBuilder<CategoryBloc, CategoryState>(
                      builder: (context, catState) {
                        List<CategoryEntity> categories = [];
                        if (catState is CategoriesLoaded) {
                          categories = catState.categories;
                        }

                        return DropdownButtonFormField<String?>(
                          value: _selectedCategoryId,
                          decoration: const InputDecoration(
                            prefixIcon: Icon(Icons.category_outlined),
                          ),
                          hint: const Text('No Category'),
                          items: [
                            const DropdownMenuItem<String?>(
                              value: null,
                              child: Text('No Category'),
                            ),
                            ...categories.map(
                              (cat) => DropdownMenuItem(
                                value: cat.id,
                                child: Row(
                                  children: [
                                    Text(cat.icon),
                                    const SizedBox(width: 8),
                                    Text(cat.name),
                                  ],
                                ),
                              ),
                            ),
                          ],
                          onChanged: (value) =>
                              setState(() => _selectedCategoryId = value),
                        );
                      },
                    ),
                    const SizedBox(height: 24),

                    const Text(
                      'Frequency',
                      style: TextStyle(fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 8),
                    SegmentedButton<HabitFrequency>(
                      segments: const [
                        ButtonSegment(
                          value: HabitFrequency.daily,
                          label: Text('Daily'),
                        ),
                        ButtonSegment(
                          value: HabitFrequency.weekly,
                          label: Text('Weekly'),
                        ),
                      ],
                      selected: {_frequency},
                      onSelectionChanged: (Set<HabitFrequency> newSelection) {
                        setState(() => _frequency = newSelection.first);
                      },
                    ),
                    const SizedBox(height: 24),

                    // Reminder Settings
                    ReminderSettingsWidget(
                      reminderEnabled: _reminderEnabled,
                      reminderTime: _reminderTime,
                      reminderDays: _reminderDays,
                      onReminderEnabledChanged: (value) async {
                        if (value) {
                          final granted = await di
                              .sl<NotificationService>()
                              .requestPermissions();
                          if (granted) {
                            setState(() => _reminderEnabled = true);
                          } else {
                            if (context.mounted) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                  content: Text(
                                    'Permission denied. Please enable notifications in settings.',
                                  ),
                                  backgroundColor: Colors.redAccent,
                                ),
                              );
                            }
                            setState(() => _reminderEnabled = false);
                          }
                        } else {
                          setState(() => _reminderEnabled = false);
                        }
                      },
                      onReminderTimeChanged: (value) {
                        setState(() => _reminderTime = value);
                      },
                      onReminderDaysChanged: (value) {
                        setState(() => _reminderDays = value);
                      },
                    ),
                    const SizedBox(height: 32),

                    SizedBox(
                      width: double.infinity,
                      height: 54,
                      child: FilledButton.icon(
                        onPressed: isLoading ? null : _onSavePressed,
                        icon: isLoading
                            ? const SizedBox(
                                width: 20,
                                height: 20,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: Colors.white,
                                ),
                              )
                            : const Icon(Icons.add_rounded),
                        label: Text(isLoading ? 'Saving...' : 'Create Habit'),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      },
    );
  }
}
